### ISSUE TITLE
Stacktrace when creating interserver network and transfering to other server

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#150]
```java
[18:13:19 WARN]: [Stargate] [Stargate] Error receiving BungeeCord message
[18:13:19 WARN]: net.TheDgtl.Stargate.exception.NameErrorException
[18:13:19 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.network.LocalNetwork.addPortal(LocalNetwork.java:90)
[18:13:19 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.listeners.StargateBungeePluginMessageListener.updateNetwork(StargateBungeePluginMessageListener.java:185)
[18:13:19 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.listeners.StargateBungeePluginMessageListener.onPluginMessageReceived(StargateBungeePluginMessageListener.java:108)
[18:13:19 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[18:13:19 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3212)
[18:13:19 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:38)
[18:13:19 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:7)
[18:13:19 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[18:13:19 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:13:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[18:13:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[18:13:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[18:13:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[18:13:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[18:13:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Thorinwasher** [comment]
How to reproduce:
Create a interserver portal (I flag) in a server. Connect to another server that is connected with the same mysql database. Both servers has to have bungeecoord enabled

Result will be a stacktrace thrown, everything else will work normally. There's no name duplicates

**Comment by EpicKnarvik97** [comment]
It's definitely caused by  the name check in LocalNetwork line 89.

> Create a interserver portal (I flag) in a server. Connect to another server that is connected with the same database

Does this mean the servers have a duplicate database, or do you mean two servers with distinct IDs in the same MySQL database? Are there any name duplicates, or is it a false positive?

**Comment by Thorinwasher** [comment]
So I tried to recreate this issue again, but this time everything worked as intended, no stacktraces were thrown. So I'm unsure what the issue was all about, could it have something to do with duplicate messages being sent, a glitch in bungee or something?

**Comment by Pheotis** [comment]
As this has not yet been repro'd, going to decouple this from 1.0.0.5.

**Comment by Pheotis** [comment]
Has not been reproduced recently.
