### ISSUE TITLE
Database Corruption Crash (Offline Users) [TMS 222181]

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#167]
When starting a stargate instance within a bungee network consisting of offline players and servers,
 after having migrated from both Knarvik and an older version of the Rewrite;

Startup produces a warning-level stack trace.

## Environment
Repro'd in
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating Knarvik 0.9.3.7, Test Environment unit `2-Paper-Offline-MigKnar-Modern-SQL`)
**Server Version**: `git-Paper-350` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`
And
**Plugin Version**: `ALPHA-1.0.0.4` (Migrating simulated 1.0.0.2 config, Test Environment unit `2-Spigot-Offline-MigOld-Modern-SQL`)
**Server Version**: `3491-Spigot-b081915-95d233d` (MC: 1.18.2) Implementing API Version `1.18.2-R0.1-SNAPSHOT`

With MySQL 8.0.29 running locally on Win64 via TCP/IP

## Details
```java
[17:51:39 INFO]: [Stargate] Enabling Stargate v1.0.0.4-ALPHA
[17:51:39 WARN]: [Stargate] Invalid colors for sign text. Using default colors instead...
[17:51:39 INFO]: [Stargate] Saving language file from internal path lang\en-GB\en.txt
[17:51:39 INFO]: [Stargate] Saving language file from internal path lang\en\en-GB.txt
[17:51:39 INFO]: [Stargate] Saving language file from internal path lang\en\en.txt
[17:51:39 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[17:51:39 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[17:51:40 WARN]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS PortalPositionIndex ON SG_57cab3e6c18d4b4bb0352e7c4b635830PortalPo' at line 1
[17:51:40 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[17:51:40 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[17:51:40 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[17:51:40 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.database.PortalDatabaseAPI.runStatement(PortalDatabaseAPI.java:272)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.database.PortalDatabaseAPI.createTables(PortalDatabaseAPI.java:295)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.database.PortalDatabaseAPI.<init>(PortalDatabaseAPI.java:83)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.database.PortalDatabaseAPI.<init>(PortalDatabaseAPI.java:61)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.Stargate.load(Stargate.java:305)
[17:51:40 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.Stargate.onEnable(Stargate.java:146)
[17:51:40 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:51:40 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:51:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[17:51:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[17:51:40 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[17:51:40 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[17:51:40 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[17:51:40 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[17:51:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[17:51:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17:51:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[17:51:40 INFO]: Running delayed init tasks
```

When the plugin is shut down / disabled, this also prints:

```java
[18:05:18 ERROR]: Error occurred while disabling Stargate v1.0.0.4-ALPHA (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.network.StargateRegistry.getBungeeNetworkMap()" because "this.registry" is null
        at net.TheDgtl.Stargate.Stargate.onDisable(Stargate.java:316) ~[Stargate-1.0.0.4-ALPHA.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:555) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:494) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:971) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:803) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[paper-1.18.2.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-350]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Database dump (.sql files are not allowed on github; sent via discord).

**Comment by Pheotis** [comment]
When the first player connects to the server, this stack trace is printed:
```java
[17:59:44] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.database.StorageAPI.startInterServerConnection()" because the return value of "net.TheDgtl.Stargate.Stargate.getStorageAPIStatic()" is null
[17:59:44] [Server thread/WARN]:        at net.TheDgtl.Stargate.listener.PlayerEventListener.lambda$2(PlayerEventListener.java:197)
[17:59:44] [Server thread/WARN]:        at net.TheDgtl.Stargate.action.ConditionalDelayedAction.run(ConditionalDelayedAction.java:32)
[17:59:44] [Server thread/WARN]:        at net.TheDgtl.Stargate.thread.SynchronousPopulator.cycleQueue(SynchronousPopulator.java:104)
[17:59:44] [Server thread/WARN]:        at net.TheDgtl.Stargate.thread.SynchronousPopulator.cycleQueues(SynchronousPopulator.java:83)
[17:59:44] [Server thread/WARN]:        at net.TheDgtl.Stargate.thread.SynchronousPopulator.run(SynchronousPopulator.java:38)
[17:59:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82)
[17:59:44] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415)
[17:59:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285)
[17:59:44] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429)
[17:59:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237)
[17:59:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047)
[17:59:44] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[17:59:44] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Likewise, when a server is manually switched, this prints:
```java
[18:03:58 INFO]: Central[/127.0.0.1:51420] logged in with entity id 1 at ([world]26.70529331770624, -60.0, 28.69136022478631)
[18:04:00 WARN]: java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.database.StorageAPI.startInterServerConnection()" because the return value of "net.TheDgtl.Stargate.Stargate.getStorageAPIStatic()" is null
[18:04:00 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.listener.PlayerEventListener.lambda$2(PlayerEventListener.java:197)
[18:04:00 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.action.ConditionalDelayedAction.run(ConditionalDelayedAction.java:32)
[18:04:00 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.thread.SynchronousPopulator.cycleQueue(SynchronousPopulator.java:104)
[18:04:00 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.thread.SynchronousPopulator.cycleQueues(SynchronousPopulator.java:83)
[18:04:00 WARN]:        at Stargate-1.0.0.4-ALPHA.jar//net.TheDgtl.Stargate.thread.SynchronousPopulator.run(SynchronousPopulator.java:38)
[18:04:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101)
[18:04:00 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[18:04:00 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1531)
[18:04:00 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:483)
[18:04:00 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1455)
[18:04:00 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1225)
[18:04:00 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[18:04:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Pheotis** [comment]
When a player moves, this stack trace is printed.
```java
[18:02:16] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Stargate v1.0.0.4-ALPHA
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1253) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:16) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.network.RegistryAPI.getPortal(org.bukkit.Location, net.TheDgtl.Stargate.gate.structure.GateStructureType)" because the return value of "net.TheDgtl.Stargate.Stargate.getRegistryStatic()" is null
        at net.TheDgtl.Stargate.listener.MoveEventListener.onAnyMove(MoveEventListener.java:99) ~[?:?]
        at net.TheDgtl.Stargate.listener.MoveEventListener.onPlayerMove(MoveEventListener.java:70) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

When a player tries to interact with a stargate, this is printed:
```java
[18:03:05] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Stargate v1.0.0.4-ALPHA
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:505) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:496) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1547) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.TheDgtl.Stargate.network.RegistryAPI.getPortal(org.bukkit.Location, net.TheDgtl.Stargate.gate.structure.GateStructureType)" because the return value of "net.TheDgtl.Stargate.Stargate.getRegistryStatic()" is null
        at net.TheDgtl.Stargate.listener.PlayerEventListener.onPlayerInteract(PlayerEventListener.java:61) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 22 more
```

**Comment by EpicKnarvik97** [comment]
Most of these errors are a result of the registry not being able to load at all beacause of an SQL exception. `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS PortalPositionIndex ON SG_57cab3e6c18d4b4bb0352e7c4b635830PortalPo' at line 1` is the only "real" error.

It seems CREATE INDEX IF NOT EXISTS does not work, This needs to be changed to some valid syntax One additional problem I see is that PortalPositionIndex is not unique between servers. Duplicate indexes will cause problems.

**Comment by Thorinwasher** [comment]
I can not reproduce this when using MariaDB. 

Also when changing to a remote database, everything on the previous save will be wiped. This should therefore be reproduceable  without migrating from an old save.

**Comment by EpicKnarvik97** [comment]
I've added 884a160, as the previous change created infinite un-named indexes for MySQL. The new behavior ignores errors when trying to create the index, and prints a fine message instead. It might be harder to discover any actual problems in the query if they appear later, but this should create exactly one named index, and not throw an exception which crashes the whole plugin.

**Comment by EpicKnarvik97** [comment]
@Pheotis This should be fixed in theory. You can close it if you cannot find anything during testing.

**Comment by Pheotis** [comment]
Noted!
