### ISSUE TITLE
Unable to use ssl for spigot 1.15

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-rewritten/Stargate-Bukkit#202]
How to replicate:
- Have useRemoteDatabase and useSSL set to true in the config
- Start a spigot 1.15 instance
 
On startup this stacktrace gets thrown:
```
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet successfully received from the server was 53 milliseconds ago.  The last packet sent successfully to the server was 48 milliseconds ago.
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at net.TheDgtl.Stargate.database.MySqlDatabase.setupMySql(MySqlDatabase.java:78) ~[?:?]
        at net.TheDgtl.Stargate.database.MySqlDatabase.<init>(MySqlDatabase.java:51) ~[?:?]
        at net.TheDgtl.Stargate.database.PortalDatabaseAPI.loadDatabase(PortalDatabaseAPI.java:241) ~[?:?]
        at net.TheDgtl.Stargate.database.PortalDatabaseAPI.load(PortalDatabaseAPI.java:559) ~[?:?]
        at net.TheDgtl.Stargate.database.PortalDatabaseAPI.<init>(PortalDatabaseAPI.java:62) ~[?:?]
        at net.TheDgtl.Stargate.Stargate.load(Stargate.java:511) ~[?:?]
        at net.TheDgtl.Stargate.Stargate.onEnable(Stargate.java:151) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
```
This will not happen if ssl=false by some reason. I really have no clue on this one

**Comment by EpicKnarvik97** [comment]
Are you certain the database you are connecting to supports ssl in that way? Does it work on 1.18.2? This error merely says it was unable to connect to the database. There could be a number of reasons why enabling SSL could make the configuration invalid.

**Comment by Thorinwasher** [comment]
It works on 1.18.2, so I'm just guessing it's a 1.15 incompatability.

**Comment by Thorinwasher** [comment]
It works now, so let's just close this
