### ISSUE TITLE
[TMS TMP009] The furnace minecart exception is not caught on spigot 1.15.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#257]
This is a furnace minecart going through a portal on spigot 1.15 (the min instance in the continuum suite of tests).

```java
[17:14:15] [Server thread/WARN]: [Stargate] Task #9 for Stargate v1.0.0.13-ALPHA generated an exception
java.lang.NoSuchMethodError: 'int org.bukkit.entity.minecart.PoweredMinecart.getFuel()'
        at org.sgrewritten.stargate.network.portal.Teleporter.teleportPoweredMinecart(Teleporter.java:345) ~[?:?]
        at org.sgrewritten.stargate.network.portal.Teleporter.teleport(Teleporter.java:329) ~[?:?]
        at org.sgrewritten.stargate.network.portal.Teleporter.betterTeleport(Teleporter.java:246) ~[?:?]
        at org.sgrewritten.stargate.network.portal.Teleporter.lambda$4(Teleporter.java:165) ~[?:?]
        at org.sgrewritten.stargate.action.SupplierAction.run(SupplierAction.java:24) ~[?:?]
        at org.sgrewritten.stargate.thread.SynchronousPopulator.cycleQueue(SynchronousPopulator.java:106) ~[?:?]
        at org.sgrewritten.stargate.thread.SynchronousPopulator.cycleQueues(SynchronousPopulator.java:79) ~[?:?]
        at org.sgrewritten.stargate.thread.SynchronousPopulator.run(SynchronousPopulator.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-3b314f5-e2790ae]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1030) [spigot.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot.jar:git-Spigot-3b314f5-e2790ae]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot.jar:git-Spigot-3b314f5-e2790ae]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by Thorinwasher** [comment]
Really? The 1.15 api does not have the getFuel method?

This method is necessary to be able to (with great effort) change the direction the minecart is going. The inaccessibility of that method basically makes it impossible to change the direction of the minecart

As this is 1.15, I doubt I can unit test it, as furnace minecarts are not implemented yet in mockbukkit, and definitely aren't in 1.1.5

**Comment by Pheotis** [comment]
True.

The original plan to handle this was simply not to allow minecarts on non-paper and outdated (with a console warning )

From what I can tell, that warning should have been triggered here (instead of that stack trace).
