### ISSUE TITLE
Failed to TP to Micro Gate

### ISSUE THREAD

**Issue by dosluke** [stargate-rewritten/Stargate-Bukkit#293]
### Bug Description

Teleporting to the shown gate causes an exception

### Reproduction Steps

 X 
-.-

this gate structure, then tp to it from another gate.

### Desired Behaviour

Tp through to desired gate

### Observed Behaviour

I popped out the other side of the portal i tried to initiate the TP from. Thats a graceful failure. Stack trace appears in console.

### Trace Logs

This trace is what appears in Console:
```java
[18:53:45] [Server thread/INFO]: [Stargate] Trying to teleport entity, initial velocity: 0.007620358820531692,0.0,-0.21521376622536081, new velocity: 0.007620358820531692,0.0,-0.21521376622536081
[18:53:45] [Server thread/INFO]: [Stargate] Formatted TranslatableMessage 'TELEPORT' to 'Teleported!'
[18:53:45] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Stargate v1.0.0.11-ALPHA
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1350) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:42) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.util.thread.IAsyncTaskHandler.br(SourceFile:115) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1109) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3749-Spigot-7da74da-d9324b4]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.util.Vector.clone()" because "vector" is null
        at net.TheDgtl.Stargate.vectorlogic.MatrixVectorOperation.performToRealSpaceOperation(MatrixVectorOperation.java:93) ~[?:?]
        at net.TheDgtl.Stargate.gate.Gate.getLocation(Gate.java:274) ~[?:?]
        at net.TheDgtl.Stargate.gate.Gate.getExit(Gate.java:200) ~[?:?]
        at net.TheDgtl.Stargate.network.portal.AbstractPortal.getExit(AbstractPortal.java:392) ~[?:?]
        at net.TheDgtl.Stargate.network.portal.Teleporter.<init>(Teleporter.java:68) ~[?:?]
        at net.TheDgtl.Stargate.network.portal.AbstractPortal.teleportHere(AbstractPortal.java:246) ~[?:?]
        at net.TheDgtl.Stargate.network.portal.AbstractPortal.doTeleport(AbstractPortal.java:271) ~[?:?]
        at net.TheDgtl.Stargate.listener.MoveEventListener.onAnyMove(MoveEventListener.java:143) ~[?:?]
        at net.TheDgtl.Stargate.listener.MoveEventListener.onPlayerMove(MoveEventListener.java:93) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

This is the SG trace file:
```yaml
defaultGateNetwork: central
language: en
bungee:
  usingBungee: false
  useRemoteDatabase: false
  remoteDatabaseSettings:
    advancedDatabaseConfiguration: false
    driver: MySQL
    useSSL: true
networkLimit: -1
useEconomy: false
taxAccount: ''
creationCost: 0
destructionCost: 0
usageCost: 0
gateOwnerRevenue: true
chargeFreeDestination: true
signStyle:
  defaultForeground: BLACK
  defaultBackground: WHITE
  listing: 1
  pointer: 2
gateExitSpeedMultiplier: 1
disableCustomColoredNames: false
loggingLevel: FINER
configVersion: 6
portalFile: stargate
customRemoteDatabasePrefix: SG_
destroyOnExplosion: false
handleVehicles: true
protectEntrance: true
rememberLastDestination: false
checkPortalValidity: true
handleLeashedCreatures: true
defaultTerminalNetwork: terminal
BukkitInstance: 3749-Spigot-7da74da-d9324b4 (MC: 1.19.4)
Stargate version: 1.0.0.11-ALPHA
JavaVersion: 20.0.1
OperatingSystem: Windows 10

end.gate
portal-open=END_GATEWAY
portal-closed=AIR
-=IRON_BLOCK,QUARTZ_PILLAR
S=QUARTZ_STAIRS
H=QUARTZ_SLAB
F=SMOOTH_QUARTZ,#WOOL

HFFH
S..S
-..-
S*.S
HFFH

MicroNether.gate
portal-open=END_GATEWAY
portal-closed=AIR
X=OBSIDIAN
-=OBSIDIAN

 X 
-.-

nether.gate
portal-open=NETHER_PORTAL
portal-closed=AIR
X=OBSIDIAN
-=OBSIDIAN

 XX 
X..X
-..-
X*.X
 XX 

smallnether.gate
portal-open=END_GATEWAY
portal-closed=AIR
X=OBSIDIAN
-=OBSIDIAN

 X 
-.-
X*X
 X 

water.gate
portal-open=KELP_PLANT
portal-closed=WATER
X=SEA_LANTERN
-=SEA_LANTERN

 XX 
X..X
-..-
X*.X
 XX 

wool.gate
portal-open=WATER
portal-closed=AIR
X=#WOOL
-=#WOOL

XXXXX
X...X
-...-
X.*.X
XXXXX
```

**Comment by EpicKnarvik97** [comment]
That gate is missing an exit (*) so it's not a valid design as far as I know. It being allowed to exist seems like a bug itself. Because it's missing an exit, an exception is thrown when trying to use the non-existing exit location in order to calculate the real output coordinates.

**Comment by dosluke** [comment]
> That gate is missing an exit (*) so it's not a valid design as far as I know. It being allowed to exist seems like a bug itself. Because it's missing an exit, an exception is thrown when trying to use the non-existing exit location in order to calculate the real output coordinates.

It fails to load with "*" instead of .
