### ISSUE TITLE
Stargate enters invalid state on 1.17.1.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#306]
### Bug Description

Default startgate on 1.17.1 is inoperable following server restart.

### Reproduction Steps

Start a 1.17 server with stargate as a plugin (tested with git-paper-411 for 1.17.1 using java 17).
Wait for the server to start up, then restart it.

### Desired Behaviour

The plugin should not crash.

### Observed Behaviour

The plugin crashes on all subsequent startups and thus fails to enable.

### Trace Logs

```
[21:03:09 INFO]: [Stargate] Enabling Stargate v1.0.0.14-ALPHA
[21:03:10 ERROR]: Error occurred while enabling Stargate v1.0.0.14-ALPHA (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/output/UnsynchronizedByteArrayOutputStream
        at org.apache.tika.parser.txt.CharsetDetector.setText(CharsetDetector.java:239) ~[Stargate-1.0.0.14-ALPHA.jar:?]        at org.sgrewritten.stargate.util.FileHelper.getBufferedReader(FileHelper.java:54) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.sgrewritten.stargate.formatting.StargateLanguageManager.loadLanguageFile(StargateLanguageManager.java:204) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.sgrewritten.stargate.formatting.StargateLanguageManager.loadLanguage(StargateLanguageManager.java:129) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.sgrewritten.stargate.formatting.StargateLanguageManager.setLanguage(StargateLanguageManager.java:112) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.sgrewritten.stargate.Stargate.load(Stargate.java:589) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.sgrewritten.stargate.Stargate.onEnable(Stargate.java:179) ~[Stargate-1.0.0.14-ALPHA.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-411]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-411]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 17 more
```

### Other Information

Using the latest nightly for 1.0.0.14

**Comment by Thorinwasher** [comment]
Dropping 1.17
