### ISSUE TITLE
Core is unusable on spigot.

### ISSUE THREAD

**Issue by Pheotis** [stargate-rewritten/Stargate-Bukkit#354]
### Bug Description

Attempting to create any portal on spigot results in a stack trace.

### Reproduction Steps

1. Start the latest nightly core on the latest spigot jar.
2. Attempt to build any portal.

### Desired Behaviour

Core should be functionally usable on spigot.
Any paper-specific behaviours should be NonLegacyMethod'd away.

### Observed Behaviour

```java
[INFO]: [Stargate] Checking permissions for entity CraftPlayer{name=Pheotis}
[ERROR]: Could not pass event SignChangeEvent to Stargate v1.0.0.16-NIGHTLY-3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.TileEntitySign.setMessages(TileEntitySign.java:224) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.world.level.block.entity.TileEntitySign.lambda$updateSignText$4(TileEntitySign.java:186) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.world.level.block.entity.TileEntitySign.a(TileEntitySign.java:199) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.world.level.block.entity.TileEntitySign.a(TileEntitySign.java:185) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2976) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.network.PlayerConnection.lambda$handleSignUpdate$12(PlayerConnection.java:2957) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:162) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1242) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.util.thread.IAsyncTaskHandler.A(SourceFile:136) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.bu(MinecraftServer.java:1221) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.A(MinecraftServer.java:1214) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:145) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.v_(MinecraftServer.java:1186) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1071) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4178-Spigot-342f493-d6607c7]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'boolean org.sgrewritten.stargate.api.event.StargatePreCreatePortalEvent.callEvent()'
        at org.sgrewritten.stargate.listener.BlockEventListener.onSignChange(BlockEventListener.java:193) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        ... 24 more
```

### Trace Logs

```yml
gateFolder: gates
BukkitInstance: 4178-Spigot-342f493-d6607c7 (MC: 1.20.6)
Stargate version: 1.0.0.16-NIGHTLY-3
JavaVersion: 21.0.1
OperatingSystem: Windows 11
```

### Other Information

ex. Screenshots, error messages, additional context, bugged files, etc.

**Comment by Thorinwasher** [comment]
Will keep this issue open, as there are other possibilities that could cause spigot issues
